// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated class types.

use super::*;
use baml::{BamlDecode, BamlEncode};

#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct ChatMsg {
    pub role: String,

    pub content: String,

    pub kind: String,

    pub image_idx: i64,
}

impl AsRef<ChatMsg> for ChatMsg {
    fn as_ref(&self) -> &ChatMsg {
        self
    }
}
