use std::path::PathBuf;
use std::process::Command;

fn main() {
    // Keep model-info generation intact after the Monty cutover.
    generate_model_info();
}

fn generate_model_info() {
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let cache_path = out_dir.join("models_dev_api.json");
    let generated_path = out_dir.join("model_info_generated.rs");

    let need_download = if cache_path.exists() {
        std::fs::metadata(&cache_path)
            .and_then(|m| m.modified())
            .ok()
            .and_then(|mtime| std::time::SystemTime::now().duration_since(mtime).ok())
            .map(|age| age.as_secs() > 86_400)
            .unwrap_or(true)
    } else {
        true
    };

    if need_download {
        eprintln!("Downloading models.dev/api.json...");
        let status = Command::new("curl")
            .args(["-fsSL", "--retry", "2", "--max-time", "15", "-o"])
            .arg(&cache_path)
            .arg("https://models.dev/api.json")
            .status();
        if !matches!(status, Ok(s) if s.success()) {
            eprintln!("Warning: could not download models.dev/api.json, using fallback");
        }
    }

    let mut arms = Vec::new();
    if cache_path.exists()
        && let Ok(data) = std::fs::read_to_string(&cache_path)
        && let Ok(providers) = serde_json::from_str::<serde_json::Value>(&data)
        && let Some(obj) = providers.as_object()
    {
        for (provider, provider_info) in obj {
            let models = provider_info.get("models").and_then(|m| m.as_object());
            if let Some(models_obj) = models {
                for (model_id, info) in models_obj {
                    let ctx = info
                        .get("limit")
                        .and_then(|l| l.get("context"))
                        .and_then(|c| c.as_u64());
                    if let Some(context_limit) = ctx {
                        let full_id = format!("{provider}/{model_id}");
                        arms.push(format!("        {:?} => Some({}),", full_id, context_limit));
                    }
                }
            }
        }
    }

    if arms.is_empty() {
        arms = vec![
            r#"        "anthropic/claude-opus-4-6" => Some(200000),"#.to_string(),
            r#"        "anthropic/claude-sonnet-4-5-20250929" => Some(200000),"#.to_string(),
            r#"        "anthropic/claude-haiku-4-5-20251001" => Some(200000),"#.to_string(),
            r#"        "gpt-4o" => Some(128000),"#.to_string(),
            r#"        "openai/gpt-4o" => Some(128000),"#.to_string(),
            r#"        "gpt-4.1" => Some(1047576),"#.to_string(),
            r#"        "openai/gpt-4.1" => Some(1047576),"#.to_string(),
            r#"        "gemini-2.5-pro" => Some(1048576),"#.to_string(),
            r#"        "google/gemini-2.5-pro" => Some(1048576),"#.to_string(),
        ];
    }

    let code = format!(
        "/// Auto-generated by build.rs from models.dev/api.json\n\
         /// Returns the context window size for a given model ID.\n\
         pub fn context_window(model_id: &str) -> Option<u64> {{\n\
         \x20   match model_id {{\n\
         {}\n\
         \x20       _ => None,\n\
         \x20   }}\n\
         }}\n",
        arms.join("\n")
    );

    std::fs::write(&generated_path, code).expect("Failed to write model_info_generated.rs");
}
